In [2]:
import numpy as np

## DataTypes and Attribute's
NumPy main datatype is ndarray

In [4]:
a1 = np.array([1, 3, 5])
a1

array([1, 3, 5])

In [6]:
a2 = np.array([[1, 4.6, 2.5],
               [3, 5.3, 7.8]])

a2

array([[1. , 4.6, 2.5],
       [3. , 5.3, 7.8]])

In [7]:
a3 = np.array([[
    [1, 3, 5],
    [4, 5, 6]
],
[
    [7, 8, 9],
    [10, 11, 12]
]])

a3

array([[[ 1,  3,  5],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
# often written like this
a32 = np.array([[[1, 2, 4],
                 [3, 5, 6]],
                 [[11, 12, 13],
                  [14, 15, 16]]])

a32

array([[[ 1,  2,  4],
        [ 3,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 2, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 12)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
a3

array([[[ 1,  3,  5],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

<b> Create DataFrame from `np.array`

In [ ]:
import pandas as pd

In [20]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  4.6  2.5
1  3.0  5.3  7.8

In [ ]:
# convert back from dataframe to np.array
from_df = np.array(df)
from_df

array([[1. , 4.6, 2.5],
       [3. , 5.3, 7.8]])

In [23]:
car_sale = pd.read_csv("../introduction-to-pandas/car-sales.csv")
car_sale

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [24]:
np_car = np.array(car_sale)
np_car

array([['Toyota', 'White', 150043, 4, '$4,000.00'],
       ['Honda', 'Red', 87899, 4, '$5,000.00'],
       ['Toyota', 'Blue', 32549, 3, '$7,000.00'],
       ['BMW', 'Black', 11179, 5, '$22,000.00'],
       ['Nissan', 'White', 213095, 4, '$3,500.00'],
       ['Toyota', 'Green', 99213, 4, '$4,500.00'],
       ['Honda', 'Blue', 45698, 4, '$7,500.00'],
       ['Honda', 'Blue', 54738, 4, '$7,000.00'],
       ['Toyota', 'White', 60000, 4, '$6,250.00'],
       ['Nissan', 'White', 31600, 4, '$9,700.00']], dtype=object)

In [29]:
car_sliced = car_sale[["Odometer (KM)", "Doors"]]

np_car_sliced = np.array(car_sliced)
car_sliced, np_car_sliced

(   Odometer (KM)  Doors
 0         150043      4
 1          87899      4
 2          32549      3
 3          11179      5
 4         213095      4
 5          99213      4
 6          45698      4
 7          54738      4
 8          60000      4
 9          31600      4,
 array([[150043,      4],
        [ 87899,      4],
        [ 32549,      3],
        [ 11179,      5],
        [213095,      4],
        [ 99213,      4],
        [ 45698,      4],
        [ 54738,      4],
        [ 60000,      4],
        [ 31600,      4]]))

## Creating Arrays

In [4]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [5]:
sample_array.dtype

dtype('int64')

In [7]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
ones.dtype

dtype('float64')

In [9]:
type(ones)

numpy.ndarray

In [10]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
range_array = np.arange(0, 20, 2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
random_array = np.random.randint(0, 15, size=(4, 5))
random_array

array([[ 4,  1,  1,  3,  9],
       [ 7, 13,  2, 13,  9],
       [11,  5,  2, 10,  1],
       [ 1,  2, 12,  3,  4]], dtype=int32)

In [13]:
random_array.size

20

In [14]:
random_array.shape

(4, 5)

In [17]:
random_array_2 = np.random.random(size=(3, 5))
random_array_2

array([[0.69037984, 0.03832992, 0.24231328, 0.84094421, 0.72996016],
       [0.20606918, 0.01321428, 0.85690752, 0.18850836, 0.06807541],
       [0.12647312, 0.75781417, 0.258487  , 0.07671963, 0.68975745]])

In [18]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.39554398, 0.2471886 , 0.29627034],
       [0.32403924, 0.93300658, 0.6194637 ],
       [0.14889493, 0.70741762, 0.0495803 ],
       [0.2428699 , 0.99976163, 0.74699426],
       [0.16615619, 0.53414116, 0.31339021]])