In [29]:
import numpy as np

## DataTypes and Attribute's
NumPy main datatype is ndarray

In [30]:
a1 = np.array([1, 3, 5])
a1

array([1, 3, 5])

In [31]:
a2 = np.array([[1, 4.6, 2.5],
               [3, 5.3, 7.8]])

a2

array([[1. , 4.6, 2.5],
       [3. , 5.3, 7.8]])

In [32]:
a3 = np.array([[
    [1, 3, 5],
    [4, 5, 6]
],
[
    [7, 8, 9],
    [10, 11, 12]
]])

a3

array([[[ 1,  3,  5],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
# often written like this
a32 = np.array([[[1, 2, 4],
                 [3, 5, 6]],
                 [[11, 12, 13],
                  [14, 15, 16]]])

a32

array([[[ 1,  2,  4],
        [ 3,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [34]:
a1.shape

(3,)

In [35]:
a2.shape

(2, 3)

In [36]:
a3.shape

(2, 2, 3)

In [37]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [38]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [39]:
a1.size, a2.size, a3.size

(3, 6, 12)

In [40]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [41]:
a3

array([[[ 1,  3,  5],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

<b> Create DataFrame from `np.array`

In [42]:
import pandas as pd

In [43]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  4.6  2.5
1  3.0  5.3  7.8

In [44]:
# convert back from dataframe to np.array
from_df = np.array(df)
from_df

array([[1. , 4.6, 2.5],
       [3. , 5.3, 7.8]])

In [45]:
car_sale = pd.read_csv("../introduction-to-pandas/car-sales.csv")
car_sale

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [46]:
np_car = np.array(car_sale)
np_car

array([['Toyota', 'White', 150043, 4, '$4,000.00'],
       ['Honda', 'Red', 87899, 4, '$5,000.00'],
       ['Toyota', 'Blue', 32549, 3, '$7,000.00'],
       ['BMW', 'Black', 11179, 5, '$22,000.00'],
       ['Nissan', 'White', 213095, 4, '$3,500.00'],
       ['Toyota', 'Green', 99213, 4, '$4,500.00'],
       ['Honda', 'Blue', 45698, 4, '$7,500.00'],
       ['Honda', 'Blue', 54738, 4, '$7,000.00'],
       ['Toyota', 'White', 60000, 4, '$6,250.00'],
       ['Nissan', 'White', 31600, 4, '$9,700.00']], dtype=object)

In [47]:
car_sliced = car_sale[["Odometer (KM)", "Doors"]]

np_car_sliced = np.array(car_sliced)
car_sliced, np_car_sliced

(   Odometer (KM)  Doors
 0         150043      4
 1          87899      4
 2          32549      3
 3          11179      5
 4         213095      4
 5          99213      4
 6          45698      4
 7          54738      4
 8          60000      4
 9          31600      4,
 array([[150043,      4],
        [ 87899,      4],
        [ 32549,      3],
        [ 11179,      5],
        [213095,      4],
        [ 99213,      4],
        [ 45698,      4],
        [ 54738,      4],
        [ 60000,      4],
        [ 31600,      4]]))

## Creating Arrays

In [48]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [49]:
sample_array.dtype

dtype('int64')

In [50]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
ones.dtype

dtype('float64')

In [52]:
type(ones)

numpy.ndarray

In [53]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
range_array = np.arange(0, 20, 2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
random_array = np.random.randint(0, 15, size=(4, 5))
random_array

array([[ 3,  7,  6, 10,  1],
       [10, 12,  3,  5,  8],
       [ 4, 14,  6,  3,  9],
       [ 2,  0,  4, 14, 12]], dtype=int32)

In [56]:
random_array.size

20

In [57]:
random_array.shape

(4, 5)

In [58]:
random_array_2 = np.random.random(size=(3, 5))
random_array_2

array([[0.226012  , 0.10694568, 0.22030621, 0.34982629, 0.46778748],
       [0.20174323, 0.64040673, 0.48306984, 0.50523672, 0.38689265],
       [0.79363745, 0.58000418, 0.1622986 , 0.70075235, 0.96455108]])

In [59]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.50000836, 0.88952006, 0.34161365],
       [0.56714413, 0.42754596, 0.43674726],
       [0.77655918, 0.53560417, 0.95374223],
       [0.54420816, 0.08209492, 0.3663424 ],
       [0.8508505 , 0.40627504, 0.02720237]])

In [60]:
# random value will be exact
np.random.seed(2)
random_array_4 = np.random.randint(0, 20, size=(4, 5))
random_array_4

array([[ 8, 15, 13,  8, 11],
       [18, 11,  8,  7,  2],
       [17, 11, 15,  5,  7],
       [ 3,  6,  4, 10, 11]], dtype=int32)

## Viewing Arrays and Matrices 

In [61]:
np.unique(random_array_4)

array([ 2,  3,  4,  5,  6,  7,  8, 10, 11, 13, 15, 17, 18], dtype=int32)

In [63]:
a1

array([1, 3, 5])

In [64]:
a2

array([[1. , 4.6, 2.5],
       [3. , 5.3, 7.8]])

In [65]:
a3

array([[[ 1,  3,  5],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
a1[0]

np.int64(1)

In [68]:
a2[0]

array([1. , 4.6, 2.5])

In [69]:
a3[0]

array([[1, 3, 5],
       [4, 5, 6]])

In [70]:
a3[:2, :2, :2]

array([[[ 1,  3],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [71]:
a2[1, 1]

np.float64(5.3)

In [72]:
a3[0, 0, 2]

np.int64(5)